### ISSUE TITLE
Remove debug prints on connect, add .verbose(bool)

### ISSUE THREAD

**Issue by microbuilder** [adafruit/Adafruit_WICED_Arduino#18]
When connecting there is a large amount of debug data that needs to be removed by default:

```
Joining : HOMENETWORK
Successfully joined : HOMENETWORK
Obtaining IPv4 address via DHCP
DHCP CLIENT hostname FeatherWiFi
IPv4 network ready IP: 10.0.1.34
Setting IPv6 link-local address
IPv6 network ready IP: FE80:0000:0000:0000:4639:C4FF:FEEB:BD89
Getting NTP time... success
Current time is: 2016-02-19T09:09:37.011856
```

All Serial.print should happen on the user end.

**Comment by danielcompton** [comment]
@microbuilder how did you set the hostname of the device to "FeatherWiFi"? I'm trying to set the hostname, but am having trouble working out how to do it. Thanks!
