### ISSUE TITLE
Add I2C/Wire .endTransmission(bool)

### ISSUE THREAD

**Issue by microbuilder** [adafruit/Adafruit_WICED_Arduino#36]
Re this thread, the Maple I2C drivers seem to be missing the 'bool' override for `.endTransmission` in the Wire library: https://forums.adafruit.com/viewtopic.php?f=57&t=93496&p=470758#p470758

- https://github.com/adafruit/Adafruit_WICED_Arduino/blob/master/stm32/libraries/Wire/WireBase.h#L93

As described here this should have an alternative override to indicate if we want to send the STOP condition or not: https://www.arduino.cc/en/Reference/WireEndTransmission

Cross reference the Zero Wire.h file here: https://github.com/arduino/ArduinoCore-samd/blob/master/libraries/Wire/Wire.h#L44

**Comment by hathach** [comment]
ah thanks, I didn't know about it, I will double check and fix it later.

**Comment by hathach** [comment]
Added the function to fix build error. Added the multiple message with repeated START is easy with native mcu code, but it is kind of awkward with current Arduino WireBase wrapper. We will implement it later if this has issue with any sensor device.

**Comment by hathach** [comment]
#37
