### ISSUE TITLE
I2C Still failing with MPL3115A2 sensor

### ISSUE THREAD

**Issue by hack-o-holic** [adafruit/Adafruit_WICED_Arduino#37]
As a follow up to the previous issue I was asked to open an issue here and reference our thread in the Adafruit support forums.
http://forums.adafruit.com/viewtopic.php?f=57&t=93496&p=470977#p470977

**Comment by microbuilder** [comment]
Thanks for filing this.  There are some options missing in the Maple based Wire library around the STOP condition that will need to be added since some I2C sensors have specific requirements around STOP in the message sequence.

**Comment by hathach** [comment]
#36

**Comment by hathach** [comment]
@hack-o-holic please try to pull development branch and test again with the MPL3115A2, unfortunately, I don't have the sensor with me to test with. Please let us know if that work for you or not.

**Comment by microbuilder** [comment]
You can download the development branch using this link: https://github.com/adafruit/Adafruit_WICED_Arduino/archive/development.zip

Or you can see the changes here: https://github.com/adafruit/Adafruit_WICED_Arduino/commit/fdbed69b1eb8534312307f6c57e3758f7ec0a153

Unfortunately this is one of the rare sensors that requires the STOP condition in an usual place, and neither Thach nor me happen to have one on hand, but I'll order one to test with from the shop. Sorry for the trouble.

**Comment by hack-o-holic** [comment]
Works beautifully now!  Thanks for the excellent work!
