### ISSUE TITLE
PYUSB Support

### ISSUE THREAD

**Issue by SammyHerring** [adafruit/Adafruit_WICED_Arduino#40]
Dear Adafruit Users,

Regarding the FAQ of: 

"Q: When I try to flash using USB DFU I get the following error from feather_dfu.py: Traceback (most recent call last): File "...\hardware\Adafruit_WICED_Arduino/tools/feather_dfu.py", line 1, in <module> import usb.backend.libusb1?

A: This is probably caused by an old version of pysub. Update your pyusb version to 1.0b or higher via the following command:

pip install --upgrade pyusb
Also make sure that you have installed the proper Windows driver .inf files so that libusb can access the device via the correct USB VID and PID combinations."

I am still receiving this error regardless of my version of pyusb that I have installed - I have tried the Adafruit forum community with no luck, so I thought I would try GitHub. I was wondering if anyone would know of any alternative causes of this error?

---
OS: Mac OS X El Capitan (latest)
Arduino IDE: 1.6.8

Thanks,

Sam

**Comment by hathach** [comment]
Sorry to say this, but git issue is not really for support ticket, could you provide the forum link, we will point support team to that topic
