### ISSUE TITLE
Add missing .pulseIn Function

### ISSUE THREAD

**Issue by microbuilder** [adafruit/Adafruit_WICED_Arduino#60]
.pulseIn isn't present in Arduino_STM32 except with the F1 core ... support should be added to the repo to enable this function for WICED, re: https://forums.adafruit.com/viewtopic.php?f=57&t=104028&p=521671#p520736

**Comment by microbuilder** [comment]
Cross reference: https://github.com/rogerclarkmelbourne/Arduino_STM32/search?utf8=%E2%9C%93&q=pulsein

**Comment by hathach** [comment]
thanks, the microDelay() is also not accurate with WICED as well #46 . Need to address that to get this done correctly.

**Comment by hathach** [comment]
code from Arduino_STM32 seems to be test code, not work quite we like. I need to pull out code from avr core and port it to wiced. It works pretty precise, I have tested it using pulse from another UNO.
