### ISSUE TITLE
Verify All `While (!Serial)` loops

### ISSUE THREAD

**Issue by microbuilder** [adafruit/Adafruit_WICED_Arduino#62]
All [examples](https://github.com/adafruit/Adafruit_WICED_Arduino/tree/master/libraries/AdafruitWicedExamples) should be checked so that the initial `Serial` check waiting for Serial Monitor to be opened includes a 'delay' to avoid issues with RTOS task switching:

```
while (!Serial)
{
  /* Delay required to avoid RTOS task switching problems */
  delay(10);
}
```

Or alternatively:

```
while (!Serial) { yield(); }
```

**Comment by hathach** [comment]
all examples already has delay(1). Only a few like Blink that user modifies since it does not use Serial. Though, I will add the comment about the RTOS task to make it clearer.
