### ISSUE TITLE
ISO8601 Timestamp Error

### ISSUE THREAD

**Issue by microbuilder** [adafruit/Adafruit_WICED_Arduino#71]
There seems to be an issue with the ISO8601 timestamp function that acts as a wrapper to the underlying function in the WICED library. Testing required to see if we can find a local work around for this issue, see: https://forums.adafruit.com/viewtopic.php?f=57&t=112269

**Comment by hathach** [comment]
bug is described here https://community.cypress.com/message/16800#16800
