### ISSUE TITLE
Featherlib does not match BSP version

### ISSUE THREAD

**Issue by NickWaterton** [adafruit/Adafruit_WICED_Arduino#76]
BSP says that it is v 0.6.6, but featherlib is still v 0.6.5. This generates the warning message "feather lib library does not match BSP version, please upgrade featherlib" (or words to that effect, can't remember exactly).

**Comment by hathach** [comment]
0.6.6 is mean to fix dfu driver issue with windows, featherlib does not has any changes. We DID forgot to increase featherlib version --> annoyed warning but it is harmless. We will fix it in the next release. Thank you for reporting
