### ISSUE TITLE
The list of serial ports is not detected when used in Arduino IDE

### ISSUE THREAD

**Issue by chanhyeoni** [adafruit/Adafruit_WICED_Arduino#77]
Can you recommend me some troubleshooting techniques when serial ports are not detected in Arduino IDE? I tried other boards, and the list of ports is displayed perfectly. I appreciate any help.

**Comment by microbuilder** [comment]
Can you please post this on the Adafruit support forum? Github issues are only for code related problems and pull requests, thanks. The support staff doesn't receive email alerts for these issues.

You may want to try reflashing FeatherLib, though: https://learn.adafruit.com/introducing-the-adafruit-wiced-feather-wifi/faqs#faq-6
