### ISSUE TITLE
Feather.printVersions() gives warning

### ISSUE THREAD

**Issue by n7jti** [adafruit/Adafruit_WICED_Arduino#79]
Feather.printVersions() gives the following output:

```
Bootloader  : 1.0.0
WICED SDK   : 3.5.2
FeatherLib  : 0.6.5
Arduino API : 0.6.6

WARNING: Featherlib & Arduino library version are not matched
Please update Featherlib or Arduino library if possible
```
However, the currently available version of the FeatherLIb is 0.6.5 and this DOES NOT match the currrently avaiable version of the Arduino API.  All of the version numbers above appear to match what is available in the repository.  So there is no update available for either the Featherlib or Arduino library. 

Please provide the missing update to the feather lib, or suppress the unnecessary warning in Feather.printVersions()

**Comment by hathach** [comment]
duplicate to #76 

0.6.6 is mean to fix dfu driver issue with windows, featherlib does not has any changes. We DID forgot to increase featherlib version --> annoyed warning but it is harmless. We will fix it in the next release. Thank you for reporting
